// ─────────────────────────────────────
//  BundleBasket — Fashion Data
//  Fully data-driven. Each bundle: title, description,
//  image, category, tags[], products[].
//  Each product: name, brand, price, image, link,
//  color, size (optional), category, icon.
// ─────────────────────────────────────

const FASHION_CATEGORIES = [
  {
    id: 'formal',
    title: 'Interview & Formal Wear',
    subtitle: 'Make the right first impression',
    description: 'Professionally curated outfits for interviews, office wear, business meetings, and corporate events.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&q=80',
    gradient: 'linear-gradient(160deg, rgba(10,15,35,0.82) 0%, rgba(15,35,80,0.70) 60%, rgba(10,15,35,0.55) 100%)',
    accentColor: '#2563eb',
    accentLight: '#dbeafe',
    icon: '👔',
  },
  {
    id: 'casual',
    title: 'Casual Wear',
    subtitle: 'Effortlessly everyday',
    description: 'Perfect outfits for college, weekends, vacations and daily wear.',
    image: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=900&q=80',
    gradient: 'linear-gradient(160deg, rgba(10,25,15,0.80) 0%, rgba(20,80,40,0.68) 60%, rgba(10,25,15,0.50) 100%)',
    accentColor: '#16a34a',
    accentLight: '#dcfce7',
    icon: '👕',
  },
  {
    id: 'premium',
    title: 'Premium Looks',
    subtitle: 'Dress for the extraordinary',
    description: 'Luxury outfits for parties, weddings, premium dinners and special occasions.',
    image: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?w=900&q=80',
    gradient: 'linear-gradient(160deg, rgba(30,10,5,0.84) 0%, rgba(100,40,10,0.70) 60%, rgba(30,10,5,0.52) 100%)',
    accentColor: '#b45309',
    accentLight: '#fef3c7',
    icon: '✨',
  },
];

// ── FORMAL / INTERVIEW BUNDLES ──
const FASHION_BUNDLES = {

  formal: [
    {
      id: 'formal-1',
      categoryId: 'formal',
      title: 'Interview Ready Bundle',
      description: 'Everything you need to nail your first impression at any job interview. Crisp, confident, and complete.',
      image: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4f7f?w=900&q=80',
      tags: ['Job Interview', 'Entry Level', 'Corporate', 'Complete Look'],
      products: [
        {
          id: 'p1', name: 'Slim Fit Formal Shirt', brand: 'Peter England',
          price: 999, color: 'Sky Blue', size: '40',
          icon: '👕', category: 'Shirt',
          image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p2', name: 'Slim Fit Formal Trouser', brand: 'Raymond',
          price: 1499, color: 'Charcoal Black', size: '32',
          icon: '👖', category: 'Trouser',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p3', name: 'Oxford Leather Shoes', brand: 'Bata',
          price: 1799, color: 'Dark Brown', size: '9',
          icon: '👞', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&q=80',
          link: 'https://www.bata.in/',
        },
        {
          id: 'p4', name: 'Analog Leather Watch', brand: 'Titan',
          price: 2499, color: 'Brown Leather',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.titan.co.in/',
        },
        {
          id: 'p5', name: 'Leather Belt', brand: 'Woodland',
          price: 899, color: 'Brown',
          icon: '🪢', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1624222247344-550fb60fe8ff?w=400&q=80',
          link: 'https://www.woodlandworldwide.com/',
        },
        {
          id: 'p6', name: 'Laptop Bag', brand: 'Skybags',
          price: 1999, color: 'Black',
          icon: '💼', category: 'Bag',
          image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
          link: 'https://www.skybags.co.in/',
        },
      ],
      discount: 18,
    },
    {
      id: 'formal-2',
      categoryId: 'formal',
      title: 'Software Engineer Bundle',
      description: 'Smart-casual for the modern tech workplace. Professional yet relaxed — perfect for startup offices and tech campuses.',
      image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=900&q=80',
      tags: ['Tech Office', 'Smart Casual', 'Startup', 'Daily Wear'],
      products: [
        {
          id: 'p7', name: 'Oxford Cotton Shirt', brand: 'Allen Solly',
          price: 1299, color: 'Light Grey', size: '42',
          icon: '👕', category: 'Shirt',
          image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p8', name: 'Chino Trousers', brand: 'Van Heusen',
          price: 1799, color: 'Navy Blue', size: '32',
          icon: '👖', category: 'Trouser',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p9', name: 'Casual Derby Shoes', brand: 'Clarks',
          price: 2999, color: 'Tan Brown', size: '9',
          icon: '👟', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p10', name: 'Smart Casual Watch', brand: 'Fossil',
          price: 4999, color: 'Silver Steel',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p11', name: 'Slim Tech Backpack', brand: 'Wildcraft',
          price: 1599, color: 'Charcoal',
          icon: '🎒', category: 'Bag',
          image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 15,
    },
    {
      id: 'formal-3',
      categoryId: 'formal',
      title: 'Corporate Executive Bundle',
      description: 'Command every boardroom. A power-dressing bundle for senior professionals who mean business.',
      image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=900&q=80',
      tags: ['Executive', 'Boardroom', 'Senior', 'Power Dressing'],
      products: [
        {
          id: 'p12', name: 'Premium Formal Shirt', brand: 'Louis Philippe',
          price: 1899, color: 'White', size: '42',
          icon: '👕', category: 'Shirt',
          image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p13', name: 'Tailored Suit Trouser', brand: 'Raymond',
          price: 2499, color: 'Charcoal Grey', size: '34',
          icon: '👖', category: 'Trouser',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p14', name: 'Silk Woven Tie', brand: 'Park Avenue',
          price: 699, color: 'Navy Stripe',
          icon: '👔', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p15', name: 'Genuine Leather Shoes', brand: 'Hush Puppies',
          price: 3499, color: 'Black', size: '9',
          icon: '👞', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p16', name: 'Chronograph Watch', brand: 'Titan Edge',
          price: 7999, color: 'Gold Steel',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.titan.co.in/',
        },
        {
          id: 'p17', name: 'Executive Leather Briefcase', brand: 'Hidesign',
          price: 4999, color: 'Dark Tan',
          icon: '💼', category: 'Bag',
          image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 20,
    },
    {
      id: 'formal-4',
      categoryId: 'formal',
      title: 'First Day At Office Bundle',
      description: 'Walk in confident on day one. Fresh, polished, and ready to make a lasting impression with your new team.',
      image: 'https://images.unsplash.com/photo-1573497491208-6b1acb260507?w=900&q=80',
      tags: ['First Day', 'New Job', 'Office Ready', 'Fresh Start'],
      products: [
        {
          id: 'p18', name: 'Check Formal Shirt', brand: 'Arrow',
          price: 1499, color: 'Blue Check', size: '40',
          icon: '👕', category: 'Shirt',
          image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p19', name: 'Flat-Front Formal Pant', brand: 'Park Avenue',
          price: 1799, color: 'Dark Navy', size: '32',
          icon: '👖', category: 'Trouser',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p20', name: 'Leather Monk Strap Shoes', brand: 'Bata',
          price: 2199, color: 'Black', size: '8',
          icon: '👞', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&q=80',
          link: 'https://www.bata.in/',
        },
        {
          id: 'p21', name: 'Classic Analog Watch', brand: 'Titan Raga',
          price: 3299, color: 'Silver',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.titan.co.in/',
        },
        {
          id: 'p22', name: 'Formal Leather Belt', brand: 'Levis',
          price: 999, color: 'Black',
          icon: '🪢', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1624222247344-550fb60fe8ff?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p23', name: 'Slim Office Bag', brand: 'Safari',
          price: 1799, color: 'Dark Brown',
          icon: '💼', category: 'Bag',
          image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 16,
    },
    {
      id: 'formal-5',
      categoryId: 'formal',
      title: 'Business Meeting Bundle',
      description: 'Impeccable from boardroom to client dinner. Curated for professionals who want to look sharp and purposeful.',
      image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=900&q=80',
      tags: ['Client Meeting', 'Business Travel', 'Polished', 'Professional'],
      products: [
        {
          id: 'p24', name: 'Herringbone Formal Shirt', brand: 'Louis Philippe',
          price: 1699, color: 'Light Blue', size: '42',
          icon: '👕', category: 'Shirt',
          image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p25', name: 'Wool Blend Trouser', brand: 'Marks & Spencer',
          price: 2999, color: 'Steel Grey', size: '34',
          icon: '👖', category: 'Trouser',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p26', name: 'Brogue Oxford Shoes', brand: 'Red Tape',
          price: 2799, color: 'Tan', size: '10',
          icon: '👞', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p27', name: 'Slim Silk Tie', brand: 'Arrow',
          price: 899, color: 'Burgundy',
          icon: '👔', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'p28', name: 'Luxury Automatic Watch', brand: 'Titan Nebula',
          price: 9999, color: 'Rose Gold',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.titan.co.in/',
        },
        {
          id: 'p29', name: 'Leather Portfolio Bag', brand: 'Hidesign',
          price: 5999, color: 'Cognac Brown',
          icon: '💼', category: 'Bag',
          image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 20,
    },
  ],

  // ── CASUAL BUNDLES ──
  casual: [
    {
      id: 'casual-1',
      categoryId: 'casual',
      title: 'Weekend Chill Bundle',
      description: 'Your go-to look for coffee runs, casual outings, and laid-back weekends. Comfortable, stylish, effortless.',
      image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=900&q=80',
      tags: ['Weekend', 'Casual', 'Everyday', 'Comfortable'],
      products: [
        {
          id: 'c1', name: 'Oversized Graphic Tee', brand: 'HRX by Hrithik Roshan',
          price: 699, color: 'Washed Black', size: 'L',
          icon: '👕', category: 'Top',
          image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c2', name: 'Slim Fit Jeans', brand: 'Levis 511',
          price: 2499, color: 'Dark Indigo', size: '32',
          icon: '👖', category: 'Jeans',
          image: 'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c3', name: 'Classic Sneakers', brand: 'Nike Air Force 1',
          price: 7495, color: 'White', size: '9',
          icon: '👟', category: 'Sneakers',
          image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c4', name: 'Minimalist Watch', brand: 'Daniel Wellington',
          price: 3999, color: 'Black Mesh',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c5', name: 'Canvas Crossbody Bag', brand: 'The Souled Store',
          price: 799, color: 'Olive Green',
          icon: '👜', category: 'Bag',
          image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 12,
    },
    {
      id: 'casual-2',
      categoryId: 'casual',
      title: 'College Campus Bundle',
      description: 'Stand out on campus every day. Trendy, comfortable, and budget-friendly for the college lifestyle.',
      image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=900&q=80',
      tags: ['College', 'Campus', 'Student', 'Trendy'],
      products: [
        {
          id: 'c6', name: 'Polo T-Shirt', brand: 'U.S. Polo Assn.',
          price: 999, color: 'Navy Blue', size: 'M',
          icon: '👕', category: 'Top',
          image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c7', name: 'Cargo Joggers', brand: 'Roadster',
          price: 1299, color: 'Khaki', size: '30',
          icon: '👖', category: 'Bottoms',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c8', name: 'Running Sneakers', brand: 'Puma Velocity',
          price: 3499, color: 'Black & White', size: '8',
          icon: '👟', category: 'Sneakers',
          image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c9', name: 'College Backpack', brand: 'Wildcraft',
          price: 1499, color: 'Grey', 
          icon: '🎒', category: 'Bag',
          image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c10', name: 'Casual Cap', brand: 'New Era',
          price: 899, color: 'Black',
          icon: '🧢', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 14,
    },
    {
      id: 'casual-3',
      categoryId: 'casual',
      title: 'Vacation Ready Bundle',
      description: 'Breezy, bright, and beach-ready. Everything you need to look great on your next getaway.',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80',
      tags: ['Vacation', 'Beach', 'Travel', 'Summer'],
      products: [
        {
          id: 'c11', name: 'Linen Shirt', brand: 'Zara Man',
          price: 1999, color: 'Off White', size: 'L',
          icon: '👕', category: 'Shirt',
          image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c12', name: 'Printed Shorts', brand: 'Flying Machine',
          price: 999, color: 'Tropical Blue', size: '32',
          icon: '🩳', category: 'Shorts',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c13', name: 'Slip-On Sandals', brand: 'Crocs',
          price: 2299, color: 'Tan', size: '9',
          icon: '🩴', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c14', name: 'UV Sunglasses', brand: 'Ray-Ban Wayfarer',
          price: 4999, color: 'Black Tortoise',
          icon: '🕶', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'c15', name: 'Tote Beach Bag', brand: 'Baggit',
          price: 1299, color: 'Natural Jute',
          icon: '👜', category: 'Bag',
          image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 13,
    },
  ],

  // ── PREMIUM BUNDLES ──
  premium: [
    {
      id: 'premium-1',
      categoryId: 'premium',
      title: 'Wedding Guest Bundle',
      description: 'Arrive in style. Curated for the sophisticated wedding guest who wants to look effortlessly luxurious.',
      image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=900&q=80',
      tags: ['Wedding', 'Formal Event', 'Luxury', 'Guest'],
      products: [
        {
          id: 'pr1', name: 'Embroidered Bandhgala', brand: 'Manyavar',
          price: 4999, color: 'Royal Blue', size: '42',
          icon: '🧥', category: 'Ethnic Wear',
          image: 'https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr2', name: 'Slim Churidar', brand: 'Manyavar',
          price: 1499, color: 'Ivory', size: '32',
          icon: '👖', category: 'Bottoms',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr3', name: 'Embroidered Jutti', brand: 'Metro Shoes',
          price: 1999, color: 'Gold Embroidered', size: '9',
          icon: '👞', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr4', name: 'Gold Cufflinks Set', brand: 'Cerruti',
          price: 2499, color: 'Gold',
          icon: '✨', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr5', name: 'Luxury Dress Watch', brand: 'Titan Regalia',
          price: 12999, color: 'Gold & Brown Leather',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.titan.co.in/',
        },
        {
          id: 'pr6', name: 'Premium Attar Perfume', brand: 'Forest Essentials',
          price: 1999, color: 'Amber & Musk',
          icon: '🌸', category: 'Fragrance',
          image: 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 22,
    },
    {
      id: 'premium-2',
      categoryId: 'premium',
      title: 'Premium Party Look Bundle',
      description: 'Own every room you walk into. A bold, fashion-forward bundle for nights that deserve to be remembered.',
      image: 'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=900&q=80',
      tags: ['Party', 'Night Out', 'Bold', 'Fashion Forward'],
      products: [
        {
          id: 'pr7', name: 'Slim Fit Blazer', brand: 'H&M',
          price: 3999, color: 'Midnight Black', size: '42',
          icon: '🧥', category: 'Blazer',
          image: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4f7f?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr8', name: 'Premium Slim Trousers', brand: 'Zara Man',
          price: 2499, color: 'Black', size: '32',
          icon: '👖', category: 'Trouser',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr9', name: 'Satin Evening Shirt', brand: 'Calvin Klein',
          price: 4499, color: 'Champagne', size: '40',
          icon: '👕', category: 'Shirt',
          image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr10', name: 'Chelsea Boots', brand: 'Steve Madden',
          price: 5999, color: 'Black Suede', size: '9',
          icon: '👢', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr11', name: 'Luxury EDP Perfume', brand: 'Armaf Club De Nuit',
          price: 2999, color: 'Deep Oud & Amber',
          icon: '🌸', category: 'Fragrance',
          image: 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr12', name: 'Designer Smart Watch', brand: 'Michael Kors',
          price: 14999, color: 'Gunmetal',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 20,
    },
    {
      id: 'premium-3',
      categoryId: 'premium',
      title: 'Premium Dinner Date Bundle',
      description: 'Elegant, understated luxury for fine dining and intimate occasions. Curated by a personal stylist.',
      image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=900&q=80',
      tags: ['Dinner', 'Date Night', 'Elegant', 'Understated'],
      products: [
        {
          id: 'pr13', name: 'Merino Turtleneck', brand: 'Marks & Spencer',
          price: 2999, color: 'Charcoal', size: 'L',
          icon: '👕', category: 'Top',
          image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr14', name: 'Tailored Dress Trousers', brand: 'Hugo Boss',
          price: 5999, color: 'Dark Navy', size: '34',
          icon: '👖', category: 'Trouser',
          image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr15', name: 'Leather Loafers', brand: 'Aldo',
          price: 4999, color: 'Cognac Brown', size: '9',
          icon: '👞', category: 'Footwear',
          image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr16', name: 'Premium EDP', brand: 'Davidoff Cool Water',
          price: 1899, color: 'Aqua Fresh',
          icon: '🌸', category: 'Fragrance',
          image: 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
        {
          id: 'pr17', name: 'Statement Watch', brand: 'Emporio Armani',
          price: 19999, color: 'Silver & Brown Croc',
          icon: '⌚', category: 'Accessory',
          image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80',
          link: 'https://www.myntra.com/',
        },
      ],
      discount: 18,
    },
  ],
};
